LR_SCHEDULER_ST_KEY = 'lr_scheduler_st'
LOSS_SCALER_ST_KEY = 'loss_scaler_st'
BEST_LOSS_KEY = 'best_loss'
TRAIN_STEP_KEY = 'train_step'
VAL_STEP_KEY = 'val_step'
OPTIMIZER_ST_KEY = 'optimizer_st'
MODEL_ST_KEY = 'model_st'
CHECKPOINT_KEY = 'checkpoint'
MODEL_ST_FILENAME = 'model_st.pt'
CHECKPOINT_FILENAME = 'checkpoint.pt'

CFG = 'cfg'
MODEL_CFG = 'model_cfg'
OPTIMIZER_CFG = 'optimizer_cfg'
LR_SCHEDULER_CFG = 'lr_scheduler_cfg'
LOSS_SCALER_CFG = 'loss_scaler_cfg'
ENV_CFG = 'environment_cfg'
TRAIN_ARGS_CFG = 'train_args_cfg'
DATALOADERS_CFG = 'dataloaders_cfg'

TRAIN = 'train'
VAL = 'val'
